exclude:
  - LICENSE
  - README.md
  - .gitattributes

timezone: Asia/Hong_Kong
soc_name: 同明相照
all_in_one_windows_url: https://www.mediafire.com/file/a1w6mk7wctx5tzq/CU_Doujin_Modpack-1.1-client.zip/file
all_in_one_mac_intel_url: https://www.mediafire.com/file/6ty0vonauvb1tb8/all_in_one_Mac_Intel.zip/file
all_in_one_mac_m1_url: https://www.mediafire.com/file/uuv91mrhem0tmaa/all_in_one_Mac_M1.zip/file
modpack_url: https://www.mediafire.com/file/dcbgky0i2g6dwqw/CU_Doujin_Modpack-1.1.zip/file
