exclude:
  - LICENSE
  - README.md
  - .gitattributes

timezone: Asia/Hong_Kong
soc_name: 同音共律
all_in_one_windows_url: https://www.mediafire.com/file/edu1zlpf8rewkjl/all_in_one_Windows.zip/file
all_in_one_mac_intel_url: https://www.mediafire.com/file/apztzcq3hcd050p/all_in_one_Mac_Intel.zip/file
all_in_one_mac_m1_url: https://www.mediafire.com/file/djn3w4ry99zmtga/all_in_one_Mac_M1.zip/file
modpack_url: https://www.mediafire.com/file/7je5caasuwr2na8/CU_Doujin_Modpack-1.2.zip/file
