exclude:
  - LICENSE
  - README.md
  - .gitattributes

timezone: Asia/Hong_Kong
soc_name: 同音共律
all_in_one_windows_url: https://www.mediafire.com/file/r2zwxliviyhhol4/all_in_one_Windows.zip/file
all_in_one_mac_intel_url: https://www.mediafire.com/file/6ty0vonauvb1tb8/all_in_one_Mac_Intel.zip/file
all_in_one_mac_m1_url: https://www.mediafire.com/file/p1tj3ojyrcdp28b/all_in_one_Mac_M1.zip/file
modpack_url: https://www.mediafire.com/file/gonpioz83yr7pdl/CU_Doujin_Modpack-1.1.zip/file
