exclude:
  - LICENSE
  - README.md
  - .gitattributes

timezone: Asia/Hong_Kong
soc_name: 同音共律
all_in_one_windows_url: https://www.mediafire.com/file/r9m0sf68yc9guak/all_in_one_Windows.zip/file
all_in_one_mac_intel_url: https://www.mediafire.com/file/jcemulsziyx1jdy/all_in_one_Mac_Intel.zip/file
all_in_one_mac_m1_url: https://www.mediafire.com/file/bvq7v2gt1mf6ieh/all_in_one_Mac_M1.zip/file
modpack_url: https://www.mediafire.com/file/cqmltpbaop4kof8/CU+Doujin+Modpack-1.2.zip/file
